name: Build and deploy Firebase

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build functions
        run: npm run build functions
      - name: Build web app
        run: npm run build idea-launch-web
        env:
          NX_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NX_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          NX_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
